// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appwish.domain;

import com.appwish.domain.FeatureDataOnDemand;
import com.appwish.domain.FeatureIntegrationTest;
import com.appwish.repository.FeatureRepository;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect FeatureIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FeatureIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FeatureIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    FeatureDataOnDemand FeatureIntegrationTest.dod;
    
    @Autowired
    FeatureRepository FeatureIntegrationTest.featureRepository;
    
    @Test
    public void FeatureIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        long count = featureRepository.count();
        Assert.assertTrue("Counter for 'Feature' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FeatureIntegrationTest.testFind() {
        Feature obj = dod.getRandomFeature();
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide an identifier", id);
        obj = featureRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Feature' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Feature' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FeatureIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        long count = featureRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Feature', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Feature> result = featureRepository.findAll();
        Assert.assertNotNull("Find all method for 'Feature' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Feature' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FeatureIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        long count = featureRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Feature> result = featureRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Feature' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Feature' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FeatureIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        Feature obj = dod.getNewTransientFeature(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Feature' identifier to be null", obj.getId());
        try {
            featureRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Feature' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FeatureIntegrationTest.testDelete() {
        Feature obj = dod.getRandomFeature();
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide an identifier", id);
        obj = featureRepository.findOne(id);
        featureRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Feature' with identifier '" + id + "'", featureRepository.findOne(id));
    }
    
}
