// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appwish.domain;

import com.appwish.domain.Idea;
import com.appwish.domain.IdeaDataOnDemand;
import com.appwish.domain.UserAccountDataOnDemand;
import com.appwish.repository.IdeaRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect IdeaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IdeaDataOnDemand: @Component;
    
    private Random IdeaDataOnDemand.rnd = new SecureRandom();
    
    private List<Idea> IdeaDataOnDemand.data;
    
    @Autowired
    UserAccountDataOnDemand IdeaDataOnDemand.userAccountDataOnDemand;
    
    @Autowired
    IdeaRepository IdeaDataOnDemand.ideaRepository;
    
    public Idea IdeaDataOnDemand.getNewTransientIdea(int index) {
        Idea obj = new Idea();
        setBody(obj, index);
        setDateCreated(obj, index);
        return obj;
    }
    
    public void IdeaDataOnDemand.setBody(Idea obj, int index) {
        String body = "body_" + index;
        obj.setBody(body);
    }
    
    public void IdeaDataOnDemand.setDateCreated(Idea obj, int index) {
        String dateCreated = "dateCreated_" + index;
        obj.setDateCreated(dateCreated);
    }
    
    public Idea IdeaDataOnDemand.getSpecificIdea(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Idea obj = data.get(index);
        BigInteger id = obj.getId();
        return ideaRepository.findOne(id);
    }
    
    public Idea IdeaDataOnDemand.getRandomIdea() {
        init();
        Idea obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return ideaRepository.findOne(id);
    }
    
    public boolean IdeaDataOnDemand.modifyIdea(Idea obj) {
        return false;
    }
    
    public void IdeaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ideaRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Idea' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Idea>();
        for (int i = 0; i < 10; i++) {
            Idea obj = getNewTransientIdea(i);
            try {
                ideaRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
