// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appwish.domain;

import com.appwish.domain.IdeaDataOnDemand;
import com.appwish.domain.IdeaIntegrationTest;
import com.appwish.repository.IdeaRepository;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect IdeaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IdeaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IdeaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    IdeaDataOnDemand IdeaIntegrationTest.dod;
    
    @Autowired
    IdeaRepository IdeaIntegrationTest.ideaRepository;
    
    @Test
    public void IdeaIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Idea' failed to initialize correctly", dod.getRandomIdea());
        long count = ideaRepository.count();
        Assert.assertTrue("Counter for 'Idea' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IdeaIntegrationTest.testFind() {
        Idea obj = dod.getRandomIdea();
        Assert.assertNotNull("Data on demand for 'Idea' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Idea' failed to provide an identifier", id);
        obj = ideaRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Idea' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Idea' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IdeaIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Idea' failed to initialize correctly", dod.getRandomIdea());
        long count = ideaRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Idea', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Idea> result = ideaRepository.findAll();
        Assert.assertNotNull("Find all method for 'Idea' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Idea' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IdeaIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Idea' failed to initialize correctly", dod.getRandomIdea());
        long count = ideaRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Idea> result = ideaRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Idea' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Idea' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IdeaIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Idea' failed to initialize correctly", dod.getRandomIdea());
        Idea obj = dod.getNewTransientIdea(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Idea' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Idea' identifier to be null", obj.getId());
        try {
            ideaRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Idea' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IdeaIntegrationTest.testDelete() {
        Idea obj = dod.getRandomIdea();
        Assert.assertNotNull("Data on demand for 'Idea' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Idea' failed to provide an identifier", id);
        obj = ideaRepository.findOne(id);
        ideaRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Idea' with identifier '" + id + "'", ideaRepository.findOne(id));
    }
    
}
