// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appwish.domain;

import com.appwish.domain.Like;
import com.appwish.domain.LikeDataOnDemand;
import com.appwish.domain.UserAccountDataOnDemand;
import com.appwish.repository.LikeRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LikeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LikeDataOnDemand: @Component;
    
    private Random LikeDataOnDemand.rnd = new SecureRandom();
    
    private List<Like> LikeDataOnDemand.data;
    
    @Autowired
    UserAccountDataOnDemand LikeDataOnDemand.userAccountDataOnDemand;
    
    @Autowired
    LikeRepository LikeDataOnDemand.likeRepository;
    
    public Like LikeDataOnDemand.getNewTransientLike(int index) {
        Like obj = new Like();
        return obj;
    }
    
    public Like LikeDataOnDemand.getSpecificLike(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Like obj = data.get(index);
        BigInteger id = obj.getId();
        return likeRepository.findOne(id);
    }
    
    public Like LikeDataOnDemand.getRandomLike() {
        init();
        Like obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return likeRepository.findOne(id);
    }
    
    public boolean LikeDataOnDemand.modifyLike(Like obj) {
        return false;
    }
    
    public void LikeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = likeRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Like' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Like>();
        for (int i = 0; i < 10; i++) {
            Like obj = getNewTransientLike(i);
            try {
                likeRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
